# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

variables:
  webAppName: 'nodejs-cicd-31177'
  azureSubscription: 'nodejsGaurav'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Building'
    jobs:
      - job: Build
        displayName: 'Building job'
        pool:
          name: $(vmImageName)
          demands:
          - npm
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'

          - script: |
              npm install -g @angular/cli
              npm install
              ng build --prod
            displayName: 'npm install and build'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

          - upload : $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    displayName: 'Deploying'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: 'Deploying to Azure App Service'
        environment: $(webAppName)
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploying to webapp'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: webAppLinux
                    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
                    appName: $(webAppName)
                    runtimeStack: 'NODE|10.10'
                    startUpCommand: 'npm run start'


